[menu]

[[menu.main]]
name = "Homeoo"

[[menu.main]]
name = "Join the Club"

[[menu.main]]
name = "Scholarships"

[[menu.main]]
name = "Grants"

[[menu.main]]
name = "News"

[[menu.main]]
name = "Contact Us"

[[menu.main]]
name = "About US"