backend:
  name: github
  repo: tech4him1/testing

display_url: https://example.com
media_folder: "assets/uploads"

collections:
  - name: "resources"
    label: "Resources"
    folder: "resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "resource-form"}
      - {label: "Title", name: "title", widget: "string"}
      - label: Resource details
        name: resource
        widget: object
        fields:
          - { name: name, label: Name, widget: string }
          - { name: type, label: Type, widget: string}
          - { name: gated, label: "Gated", widget: boolean, default: true }
          - { name: url, label: "Resource URL (optional)", widget: string, required: false }
          - { name: action, label: "Call-to-Action Text", widget: string, default: "Get the Resource" }
          - { name: description, label: "Short description for the index", widget: string }
      - {label: "Body content", name: body, widget: markdown }
