backend:
  name: git-gateway
  
media_folder: "assets/uploads"

collections:
  - label: "Settings"
    name: "Settings"
    files:
      - name: "date_settings"
        label: "Date Settings"
        file: "data/date_settings.json"
        description: "Set blackout dates"
        fields:
          - label: "Blackout Dates"
            name: "blackout_dates"
            widget: "list"
            fields:
              - {label: "Note", name: "note", widget: "string"}
              - {label: "Start Date", name: "start_date", widget: "date", format: "YYYY-MM-DD"}
              - {label: "End Date", name: "end_date", widget: "date", format: "YYYY-MM-DD"}
          - label: "Blackout Object"
            name: "blackout_obj"
            widget: "object"
            fields:
              - {label: "Note", name: "note", widget: "string"}
              - {label: "Start Date", name: "start_date", widget: "date", format: "YYYY-MM-DD"}
              - {label: "End Date", name: "end_date", widget: "date", format: "YYYY-MM-DD"}
