backend:
  name: github
  repo: tech4him1/testing

display_url: https://example.com
media_folder: "assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", "name": "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Contacts"
        name: "contacts"
        file: "/data/contacts.yml"
        fields:
          - {label: Address, name: address, widget: string}
          - label: "Phone Numbers"
            name: phone_numbers
            widget: list
            fields:
            - {label: Number, name: "number", widget: string}
          - label: "Emails"
            name: emails
            widget: list
            fields:
            - {label: Email, name: "email", widget: string}
